version: 0.0
os: linux
files:
  - source: /whatsoncloud.tar
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/copy_application.sh
      timeout: 180
      runas: root
  ApplicationStop:
    - location: scripts/start_server
      timeout: 300
      runas: root
