#!/bin/bash

db=myblog
dbuser=root
dbroot=root

if [ $# -lt 3 ]; then
	echo "Usage: $0 database user pass [import_file]"
	exit 1
fi

db=$(mysql --batch --skip-column-names -e "SHOW DATABASES LIKE '$db';" | grep "$1" > /dev/null; echo "$?")

if [ $db -eq 0 ]; then
	echo "Database already exists"
	exit 1
fi

us=$(mysql --batch --skip-column-names -e "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user='$2');")

if [ $us -eq 1 ]; then
	echo "User already exists"
	exit 1
fi

echo "CREATE DATABASE $db; GRANT ALL ON $db.* TO $2@'%' IDENTIFIED BY '$3'; FLUSH PRIVILEGES;" | mysql

